"""initial

Revision ID: b087751d9279
Revises: 
Create Date: 2026-07-02 09:57:44.914142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b087751d9279'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Needed for gen_random_uuid() on Postgres < 13 (built into core on 13+).
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('main_count', sa.Integer(), nullable=False),
    sa.Column('main_min', sa.Integer(), nullable=False),
    sa.Column('main_max', sa.Integer(), nullable=False),
    sa.Column('has_special_ball', sa.Boolean(), nullable=False),
    sa.Column('special_min', sa.Integer(), nullable=True),
    sa.Column('special_max', sa.Integer(), nullable=True),
    sa.Column('base_price_cents', sa.Integer(), nullable=False),
    sa.Column('prize_type', sa.String(), nullable=False),
    sa.Column('draw_schedule', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_key'), 'games', ['key'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('draws',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('draw_date', sa.Date(), nullable=False),
    sa.Column('draw_period', sa.String(), nullable=True),
    sa.Column('winning_main', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('winning_special', sa.Integer(), nullable=True),
    sa.Column('multiplier', sa.Integer(), nullable=True),
    sa.Column('payouts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'draw_date', 'draw_period', postgresql_nulls_not_distinct=True)
    )
    op.create_index(op.f('ix_draws_draw_date'), 'draws', ['draw_date'], unique=False)
    op.create_index(op.f('ix_draws_game_id'), 'draws', ['game_id'], unique=False)
    op.create_table('ingestion_runs',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('rows_added', sa.Integer(), nullable=False),
    sa.Column('errors', sa.String(), nullable=True),
    sa.Column('ran_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invites',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('invited_by', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invites_token'), 'invites', ['token'], unique=True)
    op.create_table('prize_rules',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('tier_key', sa.String(), nullable=False),
    sa.Column('match_main', sa.Integer(), nullable=False),
    sa.Column('match_special', sa.Boolean(), nullable=False),
    sa.Column('play_type', sa.String(), nullable=True),
    sa.Column('base_amount_cents', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'tier_key', 'play_type')
    )
    op.create_table('tickets',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('entry_method', sa.String(), nullable=False),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('add_ons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('num_draws', sa.Integer(), nullable=False),
    sa.Column('total_cost_cents', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_user_id'), 'tickets', ['user_id'], unique=False)
    op.create_table('play_lines',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('line_index', sa.Integer(), nullable=False),
    sa.Column('main_numbers', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('special_number', sa.Integer(), nullable=True),
    sa.Column('play_type', sa.String(), nullable=True),
    sa.Column('wager_cents', sa.Integer(), nullable=False),
    sa.Column('is_quick_pick', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_play_lines_ticket_id'), 'play_lines', ['ticket_id'], unique=False)
    op.create_table('ticket_results',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('play_line_id', sa.Uuid(), nullable=False),
    sa.Column('draw_id', sa.Uuid(), nullable=False),
    sa.Column('match_main_count', sa.Integer(), nullable=False),
    sa.Column('match_special', sa.Boolean(), nullable=False),
    sa.Column('tier_key', sa.String(), nullable=True),
    sa.Column('amount_won_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['draw_id'], ['draws.id'], ),
    sa.ForeignKeyConstraint(['play_line_id'], ['play_lines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_results_draw_id'), 'ticket_results', ['draw_id'], unique=False)
    op.create_index(op.f('ix_ticket_results_play_line_id'), 'ticket_results', ['play_line_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_results_play_line_id'), table_name='ticket_results')
    op.drop_index(op.f('ix_ticket_results_draw_id'), table_name='ticket_results')
    op.drop_table('ticket_results')
    op.drop_index(op.f('ix_play_lines_ticket_id'), table_name='play_lines')
    op.drop_table('play_lines')
    op.drop_index(op.f('ix_tickets_user_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_table('prize_rules')
    op.drop_index(op.f('ix_invites_token'), table_name='invites')
    op.drop_table('invites')
    op.drop_table('ingestion_runs')
    op.drop_index(op.f('ix_draws_game_id'), table_name='draws')
    op.drop_index(op.f('ix_draws_draw_date'), table_name='draws')
    op.drop_table('draws')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_games_key'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
    op.execute("DROP EXTENSION IF EXISTS pgcrypto")
